Fabrica improvements 4
datacite/bracco pull request #687
Opened 2022-12-21 15:01 UTC by bklaing2

## Purpose
Update to Format component for DOIs to suggest current MIME format types.
[Vercel Build](https://bracco-ort38lrhx-datacite.vercel.app/)

closes: https://github.com/datacite/datacite/issues/1515

## Approach
It utilizes the [mime/lite](https://www.npmjs.com/package/mime) package for getting all of the MIME types. These are then suggested to the user in a dropdown as they type.

![image](https://user-images.githubusercontent.com/43453735/208925763-aa3b5ff1-18c1-4a32-8c59-df6efbe7ab41.png)

#### Open Questions and Pre-Merge TODOs
- [ ] Currently, the component only suggests the MIME types (application/pdf, text/xml,
video/mpeg) as opposed to the file extension (PDF, XML, MPG). Should it also suggest the extensions themselves, or just suggest the extensions instead of the MIME types?

## Learning

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)

- [x] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Reviewer, please remember our [guidelines](https://datacite.atlassian.net/wiki/spaces/TEC/pages/1168375809/Pull+Request+Guidelines):

- Be humble in the language and feedback you give, ask don't tell.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language appearing negative.
- Offer suggestions on how to improve code e.g. simplification or expanding clarity.
- Ensure you give reasons for the changes you are proposing.

2022-12-21 21:12 UTC, svogt0511 reviewed
I tested in the vercel preview at https://bracco-j2a1okxv6-datacite.vercel.app/.  It shows the suggestions but there are still issues.

I have an existing doi at: https://bracco-j2a1okxv6-datacite.vercel.app/dois/10.0309%2Fformat-test-1.  It has 2 formats: application/pdf and application/pdf+jpg.  The second format is made up. When I edit that form, it indicates there are 2 formats, but their values don't show.  If I try to add a format (standard or made up) it doesn't get saved.

Same in the create doi form, it shows the list of IANA formats, but if you choose one, it doesn't save it.  Additionally, you can't create your own.

Let me know when this is fixed and I will review again.

Additionally, I got a weird warning in the console, something about invalid json and it printed out a document type definition (<!DOCTYPE...), but unfortunately I can't reproduce it. It may be unrelated.

Thanks.

2023-01-02 17:42 UTC, bklaing2 commented
@svogt0511 I've fixed the issues you addressed, and deployed a new version with the changes. Here is the [Vercel build](https://bracco-ort38lrhx-datacite.vercel.app/). Please let me know if there is anything else!

2023-01-09 20:24 UTC, svogt0511 reviewed
Looks good.  Seems to work. However, there is still one tiny issue.  Kristian specified that the 'name' of the selected value should be displayed in the field once the user picks from the IANA list.  I think this is easily done with a function that picks off of the string past the last '/' in the media type past ('application/pdf' would display 'pdf').  We can ask Kristian tomorrow in the dev meeting.  I actually think it is ok the way it is.  I think it is confusing to display the name only. 

Regarding your comment:

> Currently, the component only suggests the MIME types (application/pdf, text/xml,
video/mpeg) as opposed to the file extension (PDF, XML, MPG). Should it also suggest the extensions themselves, or just suggest the extensions instead of the MIME types?

I would go with mime types and not file extensions.  We can talk about that, as well.

2023-01-09 20:24 UTC, svogt0511 commented on app/components/doi-format.js
> +      // this.set('fragment', formatExtension);
Remove commented code.

2023-01-09 20:24 UTC, svogt0511 commented on app/components/doi-format.js
> +      // this.model.get('formats').replace(this.index, 1, [ this.fragment ]);
Remove commented code.

2023-01-09 20:24 UTC, svogt0511 commented on app/components/doi-format.js
> +          // this.set('fragment', select.searchText);
Remove commented code.

2023-01-09 20:24 UTC, svogt0511 commented on app/components/doi-format.js
> +          // this.set('fragment', select.searchText);
Remove commented code.

2023-01-09 20:24 UTC, svogt0511 commented on app/components/doi-format.js
> +      console.log(9)
Remove console.log.

2023-01-09 20:24 UTC, svogt0511 commented on app/components/doi-format.js
> +      console.log(0)
Remove console.log.

2023-01-10 03:35 UTC, svogt0511 requested changes
I meant to mark the comments need to be addressed.

2023-01-12 10:05 UTC, bklaing2 commented on app/components/doi-format.js
> +      // this.model.get('formats').replace(this.index, 1, [ this.fragment ]);
Removed this

2023-01-12 10:06 UTC, bklaing2 commented on app/components/doi-format.js
> +          // this.set('fragment', select.searchText);
Removed this

2023-01-12 10:06 UTC, bklaing2 commented on app/components/doi-format.js
> +          // this.set('fragment', select.searchText);
Removed this

2023-01-12 10:06 UTC, bklaing2 commented on app/components/doi-format.js
> +      console.log(9)
Removed this

2023-01-12 10:06 UTC, bklaing2 commented on app/components/doi-format.js
> +      console.log(0)
Removed this

2023-01-13 21:53 UTC, svogt0511 approved these changes
Looks good to me.

2023-01-13 22:09 UTC, svogt0511 commented
@kjgarza I am changing the review to 'Approved'.  This does 99.9% of what is stated in the spec except for the minor issue of changing the display of the selected format to the IANA format 'Name' instead of the 'Template'. 

At present, I don't see an option with ember-power-select that will allow us to do this, and trying to work around the ember-power-select implementation is not a viable option.  @bklaing2  and I spent a fair amount of time looking for a workaround.

I think we should consider this task done.  We can add this task as a github issue that can be taken care of at a later date.

In the meantime, you can review this and the rest of the project work in [Vercel](https://bracco-9ud7n9kdr-datacite.vercel.app/).

2023-01-14 22:57 UTC, svogt0511 commented
@kjgarza And, it looks like ember-power-select DOES have an option for customizing the display of the selected item and it DOES seem to work, so we should be able to do this as you specified in the product spec.

2023-01-15 17:19 UTC, merged