Fabrica Improvements 1 - Updated create-doi-button dropdown
datacite/bracco pull request #691
Opened 2023-01-04 11:53 UTC by bklaing2

## Purpose
Updated the look of the 'Create DOI' button dropdown to be more consistent.

## Approach
Added icons and padding to the 'Create DOI' button dropdown.
![image](https://user-images.githubusercontent.com/43453735/210549073-40d46682-0708-4572-8c7c-635882f51e96.png)
![image](https://user-images.githubusercontent.com/43453735/210549104-a8ce82f5-ea02-49d6-94e4-3c282a80eebe.png)

#### Open Questions and Pre-Merge TODOs

## Learning

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

- [ ] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Reviewer, please remember our [guidelines](https://datacite.atlassian.net/wiki/spaces/TEC/pages/1168375809/Pull+Request+Guidelines):

- Be humble in the language and feedback you give, ask don't tell.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language appearing negative.
- Offer suggestions on how to improve code e.g. simplification or expanding clarity.
- Ensure you give reasons for the changes you are proposing.

2023-01-10 04:22 UTC, svogt0511 requested changes
I was going to approve this, but Kristian requested more changes, so we should just add them to this pull request. They are:

- First the button width and height consistency. It is quiet notorious in the settings and dois tabs that the Button has a different width (and slight different height) to the other buttons.

- Second the dropdown menu. is too small, do you think you could use the same styles as in the user menu (navigation bar, top-right) ? both in terms of height ,shape and the caret direction (down). 

@bklaing2 I will address Kristian's requests which are below:

- First the button width and height consistency. It is quiet notorious in the settings and dois tabs that the Button has a different width (and slight different height) to the other buttons.

- Second the dropdown menu. is too small, do you think you could use the same styles as in the user menu (navigation bar, top-right) ? both in terms of height ,shape and the caret direction (down).

My reply:

> I will try changing the styles.  We should be able to do what you want.  However, this is what single buttons look like in Fabrica.  A couple of examples - 'Add Member', and 'Add Prefixes' are single buttons and so look less wide and rounder edges (as shown below).  If there were multiple buttons on those pages they would be formatted the third image, below:

![image](https://user-images.githubusercontent.com/4681304/211465305-7a858890-0f94-4eea-90c9-c78547f25561.png)

![image](https://user-images.githubusercontent.com/4681304/211465333-8a3dd2c8-5dda-4be4-bea5-b9fc9b405a6f.png)

![image](https://user-images.githubusercontent.com/4681304/211465363-d80773d0-dc1e-41e6-af9b-60ac40e92c0b.png)

2023-01-10 07:54 UTC, kjgarza commented
@svogt0511 I think Bryceson already addressed the first problem

2023-01-11 23:59 UTC, svogt0511 approved these changes

2023-01-12 00:01 UTC, svogt0511 commented
I made changes per requests from @kjgarza.  I am going to merge this to fabrica-improvements-main and direct Kristian to look there.  This can be re-opened if necessary.

2023-01-12 00:01 UTC, merged